import ffmpegPath from 'ffmpeg-static'
import ffprobeStatic from 'ffprobe-static'
import path from 'path'
import fs from 'fs'

/**
 * Sanitize path generated by bundlers (like Next.js Turbopack) which replace __dirname with \ROOT.
 */
function resolveBundlerPath(p: string | null | undefined): string | null {
  if (!p) return null

  // Fix Next.js Turbopack \ROOT virtual path
  let normalized = p
  if (/^[\/\\]+ROOT[\/\\]?/.test(normalized)) {
    const cleaned = normalized.replace(/^[\/\\]+ROOT[\/\\]?/, '')
    normalized = path.join(process.cwd(), cleaned)
  }

  if (fs.existsSync(normalized)) {
    return normalized
  }

  return null
}

/**
 * Scan WinGet packages directory for installed FFmpeg/FFprobe binaries on Windows.
 */
function findWinGetBinary(binaryName: string): string | null {
  if (process.platform !== 'win32') return null
  const localAppData = process.env.LOCALAPPDATA
  if (!localAppData) return null

  const wingetDir = path.join(localAppData, 'Microsoft', 'WinGet', 'Packages')
  if (!fs.existsSync(wingetDir)) return null

  try {
    const entries = fs.readdirSync(wingetDir)
    for (const entry of entries) {
      if (entry.toLowerCase().includes('ffmpeg')) {
        const pkgDir = path.join(wingetDir, entry)
        // Check pkgDir/bin or subfolder/bin
        const binDirect = path.join(pkgDir, 'bin', binaryName)
        if (fs.existsSync(binDirect)) return binDirect

        const subEntries = fs.readdirSync(pkgDir)
        for (const sub of subEntries) {
          const subBin = path.join(pkgDir, sub, 'bin', binaryName)
          if (fs.existsSync(subBin)) return subBin
        }
      }
    }
  } catch {}

  return null
}

/**
 * Returns absolute path to FFmpeg binary.
 */
export function getFFmpegPath(): string {
  if (process.env.FFMPEG_PATH && fs.existsSync(process.env.FFMPEG_PATH)) {
    return process.env.FFMPEG_PATH
  }

  const resolved = resolveBundlerPath(typeof ffmpegPath === 'string' ? ffmpegPath : null)
  if (resolved) {
    return resolved
  }

  // Direct fallback inside node_modules
  const directPath = path.join(process.cwd(), 'node_modules', 'ffmpeg-static', 'ffmpeg.exe')
  if (fs.existsSync(directPath)) {
    return directPath
  }

  // Check WinGet installation
  const wingetPath = findWinGetBinary('ffmpeg.exe')
  if (wingetPath) {
    return wingetPath
  }

  return 'ffmpeg'
}

/**
 * Returns absolute path to FFprobe binary.
 */
export function getFFprobePath(): string {
  if (process.env.FFPROBE_PATH && fs.existsSync(process.env.FFPROBE_PATH)) {
    return process.env.FFPROBE_PATH
  }

  const resolved = resolveBundlerPath(ffprobeStatic?.path)
  if (resolved) {
    return resolved
  }

  // Direct fallback inside node_modules
  const directPath = path.join(
    process.cwd(),
    'node_modules',
    'ffprobe-static',
    'bin',
    process.platform === 'win32' ? 'win32' : process.platform,
    process.arch === 'x64' ? 'x64' : process.arch,
    process.platform === 'win32' ? 'ffprobe.exe' : 'ffprobe'
  )
  if (fs.existsSync(directPath)) {
    return directPath
  }

  // Check WinGet installation
  const wingetPath = findWinGetBinary('ffprobe.exe')
  if (wingetPath) {
    return wingetPath
  }

  return 'ffprobe'
}
